version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: auction_postgres_1
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: auction_database
  redis:
    image: redis
    container_name: auction_redis_1
    ports:
    - "6379:6379"
