openapi: 3.0.0
info:
  title: Auction API
  version: 1.0.0
paths:
  /user/signup:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: OK
  /user/signin:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: OK
  /user/deposit:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
              required:
                - amount
      responses:
        '200':
          description: OK
  /bid:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                price:
                  type: number
                product_id:
                  type: string
              required:
                - price
                - product_id
      responses:
        '200':
          description: OK
  /product:
    get:
      parameters:
        - in: query
          name: online_product_only
          schema:
            type: string
            default: yes
      responses:
        '200':
          description: OK
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                starting_price:
                  type: number
                time_window:
                  type: number
              required:
                - name
                - starting_price
                - time_window
      responses:
        '200':
          description: OK
  /product/close-the-bids:
    post:
      responses:
        '200':
          description: OK